# Generated by Django 5.1.1 on 2024-09-16 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'db_table': 'Comuna',
            },
        ),
        migrations.CreateModel(
            name='loginForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='usuario')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('checkbox', models.BooleanField(default=False, verbose_name='recordarme')),
            ],
        ),
        migrations.CreateModel(
            name='modificarProductoFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('Precio', models.IntegerField(verbose_name='precio')),
                ('Oferta', models.BooleanField(default=False, verbose_name='oferta')),
                ('PrecioAnterior', models.IntegerField(default=0, verbose_name='precio anterior')),
                ('Descuento', models.IntegerField(default=0, help_text='Ingrece el porcentaje de descuento. Ejemplo: 10%', null=True, verbose_name='descuento')),
                ('tipoEnvio', models.CharField(default='', max_length=100, verbose_name='tipo de envio')),
                ('costoEnvio', models.FloatField(default=0, verbose_name='costo de envio')),
                ('Descripcion', models.TextField(verbose_name='descripcion')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
                ('comuna', models.CharField(max_length=100, verbose_name='comuna')),
                ('imagen', models.ImageField(upload_to='static/arriendo/productos', verbose_name='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'db_table': 'Region',
            },
        ),
        migrations.CreateModel(
            name='registroForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='usuario')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('password2', models.CharField(max_length=100, verbose_name='password2')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('rut', models.CharField(max_length=100, verbose_name='rut')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('password', models.CharField(max_length=2000, verbose_name='password')),
                ('telefono', models.CharField(max_length=100, verbose_name='telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('comuna', models.CharField(max_length=100, verbose_name='comuna')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=100, verbose_name='calle')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('comuna', models.CharField(max_length=100, verbose_name='comuna')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DireccionEnvio',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('pagoProcesado', models.BooleanField(default=False)),
                ('enPreparacion', models.BooleanField(default=False)),
                ('enRetiro', models.BooleanField(default=False)),
                ('retirado', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(default=1726510288.146108, max_length=100)),
                ('DireccionEnvio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.direccionenvio')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
            options={
                'db_table': 'Carrito',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('marca', models.CharField(default='', max_length=100, verbose_name='marca')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='nombre')),
                ('precio', models.IntegerField(default=0, verbose_name='precio')),
                ('oferta', models.BooleanField(blank=True, default=False, verbose_name='oferta')),
                ('precioAnterior', models.IntegerField(default=0, verbose_name='precio anterior')),
                ('descuento', models.IntegerField(default=0, help_text='Ingrece el porcentaje de descuento. Ejemplo: 10%', null=True, verbose_name='descuento')),
                ('VIN', models.CharField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='VIN')),
                ('patente', models.CharField(blank=True, default='', max_length=100, verbose_name='patente')),
                ('descripcion', models.TextField(default='', verbose_name='descripcion')),
                ('tipoEnvio', models.CharField(default='', max_length=100, verbose_name='tipo de envio')),
                ('costoEnvio', models.IntegerField(default=0, verbose_name='costo de envio')),
                ('total', models.IntegerField(default=0, verbose_name='total')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.comuna')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.region')),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0, verbose_name='cantidad')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.order')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.producto')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='default.jpg', upload_to='static/arriendo/productos', verbose_name='imagen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.producto')),
            ],
            options={
                'db_table': 'ProductoImagen',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.region'),
        ),
    ]
