# Generated by Django 3.2.25 on 2024-09-29 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0019_alter_modificarproductofrom_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1727652769.765685, max_length=100),
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(verbose_name='Monto')),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('rechazado', 'Rechazado')], default='exitoso', max_length=20)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
