# Generated by Django 5.1.1 on 2024-10-09 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_perfil_delete_registroform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1728437922.122205, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(max_length=9, unique=True, verbose_name='RUT'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='home.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección de la Empresa')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='home.perfil')),
            ],
        ),
    ]
