# Generated by Django 3.2.25 on 2024-10-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20240929_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='codigoPostal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='estado',
            field=models.CharField(default='Por definir', max_length=100, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1727824992.052109, max_length=100),
        ),
    ]
