# Generated by Django 3.2.25 on 2024-10-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20241001_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='boleta_generada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1728003204.503302, max_length=100),
        ),
    ]
