# Generated by Django 5.1.1 on 2024-10-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_order_transaction_id_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1728529798.86119, max_length=100),
        ),
    ]
