# Generated by Django 5.1.1 on 2024-10-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_perfil_direccion_alter_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1728438565.823439, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(max_length=9, verbose_name='RUT'),
        ),
    ]
