# Generated by Django 3.2.25 on 2024-10-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20241003_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='boleta_generada',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1728089259.691815, max_length=100),
        ),
    ]
