# Generated by Django 5.1.1 on 2024-10-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_order_transaction_id_alter_perfil_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1728439333.825802, max_length=100),
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
