# Generated by Django 5.1.1 on 2024-10-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_perfil_direccion_alter_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1728441254.067965, max_length=100),
        ),
    ]
