# Generated by Django 5.1.1 on 2024-10-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='perfil',
        ),
        migrations.AlterField(
            model_name='direccion',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1728605139.592487, max_length=100),
        ),
    ]
