# Generated by Django 5.1.1 on 2024-10-11 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_direccion_perfil_alter_direccion_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='home.perfil'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1728605721.765335, max_length=100),
        ),
    ]
