# Generated by Django 5.1.1 on 2024-10-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_direccion_perfil_alter_direccion_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1728698348.359055, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(max_length=10),
        ),
    ]
