# Generated by Django 5.1.1 on 2024-10-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_order_transaction_id'),
        ('home', '0024_alter_order_transaction_id'),
        ('home', '0032_alter_order_transaction_id'),
    ]

    operations = [
    ]
