# Generated by Django 5.1.1 on 2024-10-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_merge_20241019_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciudadEmpresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de la empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='comunaEmpresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna de la empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='emailEmpresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email de la empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rutEmpresa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RUT de la empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefonoEmpresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono de la empresa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1729375857.649916, max_length=100),
        ),
    ]
