# Generated by Django 5.1.1 on 2024-10-25 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_merge_20241024_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='costo_compra',
            field=models.IntegerField(default=0, null=True, verbose_name='costo compra'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='fecha inicio'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fecha_termino',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='fecha termino'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1729821752.968713, max_length=100),
        ),
    ]
