# Generated by Django 5.1.1 on 2024-10-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_home_empresa_ciudadempresa_empresa_comunaempresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='ciudadEmpresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='regionEmpresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region la empresa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1729378241.516702, max_length=100),
        ),
    ]
