# Generated by Django 5.1.1 on 2024-11-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_home_orderitem_costo_compra_orderitem_fecha_inicio_and_more'),
        ('home', '0037_alter_order_transaction_id'),
    ]

    operations = [
    ]
