# Generated by Django 5.1.1 on 2024-11-17 20:03

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_merge_20241107_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=1731873815.852374, max_length=100),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen',
            field=models.ImageField(default='default.jpg', storage=storages.backends.s3.S3Storage(), upload_to='productos/', verbose_name='Imagen principal'),
        ),
    ]
